server:
  port: 8084  # Specify your desired port number here

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_ordering
    username: root
    password: shivam123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

restaurant:
  selectionStrategy: "LOWEST_COST" # Options: "LOWEST_COST", "HIGHEST_RATING"